#!/bin/sh

case "$1" in
  start)
    echo "[lab01] starting edge-agent"
    /usr/bin/edge-agent
    echo "[lab01] edge-agent completed"
    ;;
  stop)
    ;;
  restart|reload)
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
    ;;
esac

exit 0

